baseurl = "https://www.ajitem.com"
title = "Ajitem Sahasrabuddhe"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ajitem Sahasrabuddhe"
    description = "Ajitem Sahasrabuddhe's personal website"
    keywords = "blog,developer,personal"
    info = "SOFTWARE ARCHITECT & DEVELOPER"
    avatarurl = "images/avatar.jpg"
#    footercontent = "Enter a text here."
    fixedbarContent = "Do you want to know me more private?→"
    fixedbarContentAfter = "Thank You! Please share it if you like it→"

    hideCredits = false
    hideCopyright = false

    snsShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/asahasrabuddhe/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/GreatDharmatma/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/ajitem/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Ajitem Sahasrabuddhe"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Ajitem Sahasrabuddhe"
            info = "SOFTWARE ARHCITECT & DEVELOPER"
            description = "Ajitem Sahasrabuddhe's personal website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

#            [[languages.en.menu.main]]
#                name = "About"
#                weight = 1.0
#                url = "about"
#
#            [[languages.en.menu.main]]
#                name = "Blog"
#                weight = 2.0
#                url = "posts"
#
#            [[languages.en.menu.main]]
#                name = "Projects"
#                weight = 3
#                url = "projects"
#            [[languages.en.menu.main]]
#                name = "Contact me"
#                weight = 5
#                url = "contact"
